name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go and Bun
        run: |
          sudo apt-get update -y
          sudo apt-get install -y golang
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

          # Install Bun
          curl -fsSL https://bun.sh/install | bash

      - name: Build and Run Tests
        run: ./test.sh
